[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favourites = "2LnU3ewMW3fFU6b2t3oWHVcuqjDy3CTQqHoqXztVWU5S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/Work/projects/solana-training/labs.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
